### ISSUE TITLE
Rename Additional CSS -> Additional Player View CSS

### ISSUE THREAD

**Issue by arcos** [cynicaloptimist/improved-initiative#397]
I added the following in the Additional CSS box
```css
.Traits p,
.Description p {
    margin-bottom: 10px;
}
```

But it isn't be applied. The rules don't appear in my browser inspector either. Am I doing something wrong?
