### ISSUE TITLE
Text extends out of combatant details at smaller sizes

### ISSUE THREAD

**Issue by ascendedguard** [cynicaloptimist/improved-initiative#446]
Chrome 78.0

When you resize the browser < 990px, the c-statblock containing selected character details extends too far to the right, cutting off text and hiding the scrollbar.

![image](https://user-images.githubusercontent.com/507305/68426584-6c1f9800-0176-11ea-831c-8205797095bd.png)

Issue appears to be in the following CSS (viewed in Chrome when inspecting the parent `.c-statblock`), removing the `width: 300px` appears to fix the issue:

```css
@media (max-width: 900px)
#tracker .c-statblock, #tracker .left-column, #tracker .preview.statblock, #tracker .right-column {
    width: 300px;
    max-width: 300px;
}
```
